services:
  react-app:
    image: nginx:stable-alpine
    ports:
      - "86:80"
    container_name: react-nginx
    volumes:
      - ./moodbook-app/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf