name: 빌드가 잘 되는지 테스트
on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 복사
        uses: actions/checkout@v3

      - name: 정상 작동 여부 확인을 위한 빌드
        run : |
          cd moodbook-app
          npm install
          npm run build
