name: default workflow
on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 복사
        uses: actions/checkout@v3

      - name: 정상 작동 여부 확인을 위한 빌드
        run: |
          cd moodbook-app
          npm install
          npm run build

  ssh_test:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: EC2 키 생성하기
        run : |
          echo "${{ secrets.EC2_SSH_KEY }}" > ./keypair.pem
          chmod 400 ./keypair.pem

      - name: Mac의 SSH에 접속 후 파일 생성하기
        run: |
          ssh -o StrictHostKeyChecking=no -i ./keypair.pem ubuntu@ec2-54-180-145-7.ap-northeast-2.compute.amazonaws.com \
          << 'EOF'
          cd documents
          if [ -d "ReactExer" ]; then
            echo "기존 디렉토리 존재하므로, reset만 하기"
            cd ReactExer
            git fetch origin
            git reset --hard origin/main
          else
            echo "기존 디렉토리가 없으므로, 새로 다운받음"
            git clone https://github.com/LteFroggy/ReactExer.git
            cd ReactExer
          fi
          echo "빌드 진행중"
          cd moodbook-app
          sudo chown -R ubuntu:ubuntu dist
          /home/ubuntu/.nvm/versions/node/v22.17.1/bin/npm run build
          cd ..
          echo "docker 띄우는 중"
          sudo systemctl start docker
          sudo docker compose up -d
          echo "작업 완료"
          EOF