name: Mac SSH 연결 테스트
on:
  push:
    branches:
      - main

jobs:
  ssh_test:
    runs-on: ubuntu-latest
    steps:
      - name: EC2 키 생성하기
        run : |
          echo "${{ secrets.EC2_SSH_KEY }}" > ./keypair.pem
          chmod 400 ./keypair.pem

      - name: Mac의 SSH에 접속 후 파일 생성하기
        run: |
          ssh -o StrictHostKeyChecking=no -i ./keypair.pem ec2-user@ec2-3-35-16-187.ap-northeast-2.compute.amazonaws.com \
          << EOF
          cd ~/
          echo $(pwd)
          mkdir madeByGithubActions
          echo $(ls)
          EOF
